package dev.love.winter.designsystem.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

/**
 * Component color tokens for the app
 * Contains only component-level tokens (not primitive tokens)
 */
@Immutable
data class AppColorScheme(
    val colorBackground: Color,
    val colorBackgroundContainer: Color,
    val colorBackgroundObject: Color,
    val colorBackgroundModal: Color,
    val colorBackgroundBrand: Color,
    val colorBackgroundBrandSubtle: Color,
    val colorBackgroundPositive: Color,
    val colorBackgroundWarning: Color,
    val colorBackgroundNegative: Color,
    val colorBackgroundContrast: Color,
    val colorBackgroundDisabled: Color,
    val colorBackgroundOverlay: Color,
    val colorStrokeNeutralSubtle: Color,
    val colorStrokeNeutral: Color,
    val colorStrokeNeutralStrong: Color,
    val colorStrokeBrand: Color,
    val colorStrokePositive: Color,
    val colorStrokeWarning: Color,
    val colorStrokeNegative: Color,
    val colorTextTitle: Color,
    val colorTextSubtitle: Color,
    val colorTextBody: Color,
    val colorTextCaption: Color,
    val colorTextPlaceholder: Color,
    val colorTextDisabled: Color,
    val colorTextOnColorDark: Color,
    val colorTextOnColorLight: Color,
    val colorTextOnContrast: Color,
    val colorTextLink: Color,
    val colorTextBrand: Color,
    val colorTextPositive: Color,
    val colorTextWarning: Color,
    val colorTextNegative: Color,
    val colorIconNeutralSubtle: Color,
    val colorIconNeutral: Color,
    val colorIconNeutralStrong: Color,
    val colorIconBrand: Color,
    val colorIconPositive: Color,
    val colorIconWarning: Color,
    val colorIconNegative: Color,
    val colorIconOnColorDark: Color,
    val colorIconOnColorLight: Color,
    val colorIconOnContrast: Color,
    val colorIconDisabled: Color,
)

val LightAppColorScheme = AppColorScheme(
    colorBackground = ColorBackgroundLight,
    colorBackgroundContainer = ColorBackgroundContainerLight,
    colorBackgroundObject = ColorBackgroundObjectLight,
    colorBackgroundModal = ColorBackgroundModalLight,
    colorBackgroundBrand = ColorBackgroundBrandLight,
    colorBackgroundBrandSubtle = ColorBackgroundBrandSubtleLight,
    colorBackgroundPositive = ColorBackgroundPositiveLight,
    colorBackgroundWarning = ColorBackgroundWarningLight,
    colorBackgroundNegative = ColorBackgroundNegativeLight,
    colorBackgroundContrast = ColorBackgroundContrastLight,
    colorBackgroundDisabled = ColorBackgroundDisabledLight,
    colorBackgroundOverlay = ColorBackgroundOverlayLight,
    colorStrokeNeutralSubtle = ColorStrokeNeutralSubtleLight,
    colorStrokeNeutral = ColorStrokeNeutralLight,
    colorStrokeNeutralStrong = ColorStrokeNeutralStrongLight,
    colorStrokeBrand = ColorStrokeBrandLight,
    colorStrokePositive = ColorStrokePositiveLight,
    colorStrokeWarning = ColorStrokeWarningLight,
    colorStrokeNegative = ColorStrokeNegativeLight,
    colorTextTitle = ColorTextTitleLight,
    colorTextSubtitle = ColorTextSubtitleLight,
    colorTextBody = ColorTextBodyLight,
    colorTextCaption = ColorTextCaptionLight,
    colorTextPlaceholder = ColorTextPlaceholderLight,
    colorTextDisabled = ColorTextDisabledLight,
    colorTextOnColorDark = ColorTextOnColorDarkLight,
    colorTextOnColorLight = ColorTextOnColorLightLight,
    colorTextOnContrast = ColorTextOnContrastLight,
    colorTextLink = ColorTextLinkLight,
    colorTextBrand = ColorTextBrandLight,
    colorTextPositive = ColorTextPositiveLight,
    colorTextWarning = ColorTextWarningLight,
    colorTextNegative = ColorTextNegativeLight,
    colorIconNeutralSubtle = ColorIconNeutralSubtleLight,
    colorIconNeutral = ColorIconNeutralLight,
    colorIconNeutralStrong = ColorIconNeutralStrongLight,
    colorIconBrand = ColorIconBrandLight,
    colorIconPositive = ColorIconPositiveLight,
    colorIconWarning = ColorIconWarningLight,
    colorIconNegative = ColorIconNegativeLight,
    colorIconOnColorDark = ColorIconOnColorDarkLight,
    colorIconOnColorLight = ColorIconOnColorLightLight,
    colorIconOnContrast = ColorIconOnContrastLight,
    colorIconDisabled = ColorIconDisabledLight,
)

val DarkAppColorScheme = AppColorScheme(
    colorBackground = ColorBackgroundDark,
    colorBackgroundContainer = ColorBackgroundContainerDark,
    colorBackgroundObject = ColorBackgroundObjectDark,
    colorBackgroundModal = ColorBackgroundModalDark,
    colorBackgroundBrand = ColorBackgroundBrandDark,
    colorBackgroundBrandSubtle = ColorBackgroundBrandSubtleDark,
    colorBackgroundPositive = ColorBackgroundPositiveDark,
    colorBackgroundWarning = ColorBackgroundWarningDark,
    colorBackgroundNegative = ColorBackgroundNegativeDark,
    colorBackgroundContrast = ColorBackgroundContrastDark,
    colorBackgroundDisabled = ColorBackgroundDisabledDark,
    colorBackgroundOverlay = ColorBackgroundOverlayDark,
    colorStrokeNeutralSubtle = ColorStrokeNeutralSubtleDark,
    colorStrokeNeutral = ColorStrokeNeutralDark,
    colorStrokeNeutralStrong = ColorStrokeNeutralStrongDark,
    colorStrokeBrand = ColorStrokeBrandDark,
    colorStrokePositive = ColorStrokePositiveDark,
    colorStrokeWarning = ColorStrokeWarningDark,
    colorStrokeNegative = ColorStrokeNegativeDark,
    colorTextTitle = ColorTextTitleDark,
    colorTextSubtitle = ColorTextSubtitleDark,
    colorTextBody = ColorTextBodyDark,
    colorTextCaption = ColorTextCaptionDark,
    colorTextPlaceholder = ColorTextPlaceholderDark,
    colorTextDisabled = ColorTextDisabledDark,
    colorTextOnColorDark = ColorTextOnColorDarkDark,
    colorTextOnColorLight = ColorTextOnColorLightDark,
    colorTextOnContrast = ColorTextOnContrastDark,
    colorTextLink = ColorTextLinkDark,
    colorTextBrand = ColorTextBrandDark,
    colorTextPositive = ColorTextPositiveDark,
    colorTextWarning = ColorTextWarningDark,
    colorTextNegative = ColorTextNegativeDark,
    colorIconNeutralSubtle = ColorIconNeutralSubtleDark,
    colorIconNeutral = ColorIconNeutralDark,
    colorIconNeutralStrong = ColorIconNeutralStrongDark,
    colorIconBrand = ColorIconBrandDark,
    colorIconPositive = ColorIconPositiveDark,
    colorIconWarning = ColorIconWarningDark,
    colorIconNegative = ColorIconNegativeDark,
    colorIconOnColorDark = ColorIconOnColorDarkDark,
    colorIconOnColorLight = ColorIconOnColorLightDark,
    colorIconOnContrast = ColorIconOnContrastDark,
    colorIconDisabled = ColorIconDisabledDark,
)

val LocalAppColorScheme = staticCompositionLocalOf {
    LightAppColorScheme
}