package dev.love.winter.designsystem.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

/**
 * Component color tokens for the app
 * Contains only component-level tokens (not primitive tokens)
 */
@Immutable
data class ColorScheme(
    val background: Color,
    val backgroundContainer: Color,
    val backgroundObject: Color,
    val backgroundModal: Color,
    val backgroundBrand: Color,
    val backgroundBrandSubtle: Color,
    val backgroundPositive: Color,
    val backgroundWarning: Color,
    val backgroundNegative: Color,
    val backgroundContrast: Color,
    val backgroundDisabled: Color,
    val backgroundOverlay: Color,
    val strokeNeutralSubtle: Color,
    val strokeNeutral: Color,
    val strokeNeutralStrong: Color,
    val strokeBrand: Color,
    val strokePositive: Color,
    val strokeWarning: Color,
    val strokeNegative: Color,
    val textTitle: Color,
    val textSubtitle: Color,
    val textBody: Color,
    val textCaption: Color,
    val textPlaceholder: Color,
    val textDisabled: Color,
    val textOnColorDark: Color,
    val textOnColorLight: Color,
    val textOnContrast: Color,
    val textLink: Color,
    val textBrand: Color,
    val textPositive: Color,
    val textWarning: Color,
    val textNegative: Color,
    val iconNeutralSubtle: Color,
    val iconNeutral: Color,
    val iconNeutralStrong: Color,
    val iconBrand: Color,
    val iconPositive: Color,
    val iconWarning: Color,
    val iconNegative: Color,
    val iconOnColorDark: Color,
    val iconOnColorLight: Color,
    val iconOnContrast: Color,
    val iconDisabled: Color,
)

val LightAppColorScheme = ColorScheme(
    background = BackgroundLight,
    backgroundContainer = BackgroundContainerLight,
    backgroundObject = BackgroundObjectLight,
    backgroundModal = BackgroundModalLight,
    backgroundBrand = BackgroundBrandLight,
    backgroundBrandSubtle = BackgroundBrandSubtleLight,
    backgroundPositive = BackgroundPositiveLight,
    backgroundWarning = BackgroundWarningLight,
    backgroundNegative = BackgroundNegativeLight,
    backgroundContrast = BackgroundContrastLight,
    backgroundDisabled = BackgroundDisabledLight,
    backgroundOverlay = BackgroundOverlayLight,
    strokeNeutralSubtle = StrokeNeutralSubtleLight,
    strokeNeutral = StrokeNeutralLight,
    strokeNeutralStrong = StrokeNeutralStrongLight,
    strokeBrand = StrokeBrandLight,
    strokePositive = StrokePositiveLight,
    strokeWarning = StrokeWarningLight,
    strokeNegative = StrokeNegativeLight,
    textTitle = TextTitleLight,
    textSubtitle = TextSubtitleLight,
    textBody = TextBodyLight,
    textCaption = TextCaptionLight,
    textPlaceholder = TextPlaceholderLight,
    textDisabled = TextDisabledLight,
    textOnColorDark = TextOnColorDarkLight,
    textOnColorLight = TextOnColorLightLight,
    textOnContrast = TextOnContrastLight,
    textLink = TextLinkLight,
    textBrand = TextBrandLight,
    textPositive = TextPositiveLight,
    textWarning = TextWarningLight,
    textNegative = TextNegativeLight,
    iconNeutralSubtle = IconNeutralSubtleLight,
    iconNeutral = IconNeutralLight,
    iconNeutralStrong = IconNeutralStrongLight,
    iconBrand = IconBrandLight,
    iconPositive = IconPositiveLight,
    iconWarning = IconWarningLight,
    iconNegative = IconNegativeLight,
    iconOnColorDark = IconOnColorDarkLight,
    iconOnColorLight = IconOnColorLightLight,
    iconOnContrast = IconOnContrastLight,
    iconDisabled = IconDisabledLight,
)

val DarkAppColorScheme = ColorScheme(
    background = BackgroundDark,
    backgroundContainer = BackgroundContainerDark,
    backgroundObject = BackgroundObjectDark,
    backgroundModal = BackgroundModalDark,
    backgroundBrand = BackgroundBrandDark,
    backgroundBrandSubtle = BackgroundBrandSubtleDark,
    backgroundPositive = BackgroundPositiveDark,
    backgroundWarning = BackgroundWarningDark,
    backgroundNegative = BackgroundNegativeDark,
    backgroundContrast = BackgroundContrastDark,
    backgroundDisabled = BackgroundDisabledDark,
    backgroundOverlay = BackgroundOverlayDark,
    strokeNeutralSubtle = StrokeNeutralSubtleDark,
    strokeNeutral = StrokeNeutralDark,
    strokeNeutralStrong = StrokeNeutralStrongDark,
    strokeBrand = StrokeBrandDark,
    strokePositive = StrokePositiveDark,
    strokeWarning = StrokeWarningDark,
    strokeNegative = StrokeNegativeDark,
    textTitle = TextTitleDark,
    textSubtitle = TextSubtitleDark,
    textBody = TextBodyDark,
    textCaption = TextCaptionDark,
    textPlaceholder = TextPlaceholderDark,
    textDisabled = TextDisabledDark,
    textOnColorDark = TextOnColorDarkDark,
    textOnColorLight = TextOnColorLightDark,
    textOnContrast = TextOnContrastDark,
    textLink = TextLinkDark,
    textBrand = TextBrandDark,
    textPositive = TextPositiveDark,
    textWarning = TextWarningDark,
    textNegative = TextNegativeDark,
    iconNeutralSubtle = IconNeutralSubtleDark,
    iconNeutral = IconNeutralDark,
    iconNeutralStrong = IconNeutralStrongDark,
    iconBrand = IconBrandDark,
    iconPositive = IconPositiveDark,
    iconWarning = IconWarningDark,
    iconNegative = IconNegativeDark,
    iconOnColorDark = IconOnColorDarkDark,
    iconOnColorLight = IconOnColorLightDark,
    iconOnContrast = IconOnContrastDark,
    iconDisabled = IconDisabledDark,
)

val LocalAppColorScheme = staticCompositionLocalOf {
    LightAppColorScheme
}